"""empty message

Revision ID: 88741fc1872e
Revises: 08dbe999b3b9
Create Date: 2020-09-15 14:58:51.997457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88741fc1872e'
down_revision = '08dbe999b3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
